<?php

namespace Taskeet\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Taskeet\MainBundle\Entity\User;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	public function findTodayTasksByUser(User $user)
	{
		return $this->getEntityManager()
            ->createQueryBuilder('t')
            ->where('t.startDate = ?1')
            ->andWhere('t.assignedTo = ?2')
            ->setParameters(array(1 => new \DateTime('today'), 2 => $user))
            ->getQuery()
            ->getResult();
	}
}
