<?php

namespace Taskeet\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Taskeet\MainBundle\Entity\Department;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
}
