admingenerator_generator:
    ## Global
    use_doctrine_orm: true
    use_doctrine_odm: false
    use_propel: false
    stylesheets:
         - { path: bundles/taskeetmain/css/bootstrap.css }
    overwrite_if_exists: false
    base_admin_template: TaskeetMainBundle::base_admin.html.twig
    knp_menu_class: Taskeet\MainBundle\Menu\DefaultMenuBuilder
    thumbnail_generator: ~
    dashboard_welcome_path: dashboard_welcome
    login_path: fos_user_security_login
    logout_path: fos_user_security_logout
    twig:
        use_form_resources: true
        use_localized_date: true
        date_format: d-m-Y
        datetime_format: d-m-Y H:i
        localized_date_format: medium
        localized_datetime_format: medium
        number_format:
            decimal: 0
            decimal_point: .
            thousand_separator: ,
    templates_dirs: []

#admingenerator_user:
#    login_template: AdmingeneratorUserBundle:Security:login.html.twig