generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Category
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
#        image:
#            label:            Imagen
#            formType:         single_upload
#            dbType:           string
#            addFormOptions:
#                nameable:       imageLabel
#                data_class:     Symfony\Component\HttpFoundation\File\File

builders:
    list:
        params:
            title: Categorías
            display: [name]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name]
    new:
        params:
            title: Nueva categoría
            display: [name]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando la categoría \"%object%\"|{ %object%: Category.name }|"
            display: [name]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                show: ~
    show:
        params:
            title: "Categoría \"%object%\"|{ %object%: Category.name }|"
            display: [name]
            actions:
                list: ~
                edit: ~
                new: ~
    delete: ~
