generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Department
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields: ~

builders:
    list:
        params:
            title: Lista de departamentos
            display: [name, slug, owner]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name, owner]
    new:
        params:
            title: Nuevo departamento
            display: [name, owner, users]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando el departamento \"%object%\"|{ %object%: Department.name }|"
            display: [name, slug, owner, users]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                show: ~
    show:
        params:
            title: "Departamento \"%object%\"|{ %object%: Department.name }|"
            display: [name, slug, owner, users]
            actions:
                edit: ~
                list: ~
                new: ~
    delete: ~
