generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Department
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
        users:
            label:            Usuarios
            dbType:           collection
            formType:         collection
            addFormOptions:
              widget:         fieldset
              # type:           \Taskeet\MainBundle\Form\Type\Department\EditType
              allow_add:      true
              allow_delete:   true
              by_reference:   false
              options:
                label:          Nuevo usuario
                data_class:     Taskeet\MainBundle\Entity\Department

builders:
    list:
        params:
            # credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: Departamentos
            display: [name, slug, owner]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name, owner]
    new:
        params:
            # credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: Nuevo departamento
            display: [name, owner, users]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            # credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: "Editando el departamento \"%object%\"|{ %object%: Department.name }|"
            display: [name, slug, owner, users]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                show: ~
    show:
        params:
            # credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: "Departamento \"%object%\"|{ %object%: Department.name }|"
            display: [name, slug, owner, users]
            actions:
                edit: ~
                list: ~
                new: ~
    delete: ~
