generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Department
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    fields: ~

builders:
    list:
        params:
            title: Lista de departamentos
            display: [name, slug]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name]
    new:
        params:
            title: Nuevo departamento
            display: [name]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Department.name }|"
            display: [name, slug]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Department.name }|"
            display: ~
            actions:
                edit: ~
                list: ~
                new: ~
    delete: ~
