generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Department
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields: ~
#        users:
#            formType: double_list
#        users:
#            label:            Usuarios
#            dbType:           collection
#            formType:         collection
#            addFormOptions:
#              widget:         fieldset
#              # type:           \Taskeet\MainBundle\Form\Type\Department\EditType
#              allow_add:      true
#              allow_delete:   true
#              by_reference:   false
#              options:
#                label:          Nuevo usuario
#                data_class:     Taskeet\MainBundle\Entity\Department

builders:
    list:
        params:
            title: Departamentos
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            display: [name, slug, owner]
            scopes:
                group_1:
                    "Todos": ~
                    "Mis departamentos":
                        default: true
                        filters:
                            owner: user
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name, owner, users]
    new:
        params:
            credentials: 'hasRole("ROLE_ADMIN")'
            title: Nuevo departamento
            display: [name, owner]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OPERATOR")'
            title: "Editando el departamento \"%object%\"|{ %object%: Department.name }|"
            display: [name, slug, owner]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    show:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "VIEW")'
            title: "%object%|{ %object%: Department.name }|"
            display: [name, owner, users]
            actions:
                new: ~
                list: ~
    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
