generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Department
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    fields: ~
#        users:
#            formType: collection
#            dbType: collection
#            addFormOptions:
#                widget:         table
#                sortable:       position
#                type:           doctrine_double_list
#                allow_add:      true
#                allow_delete:   true
#                by_reference:   false
#                options:
#                    label:          Nuevo usuario
##                   data_class:     Taskeet\MainBundle\Entity\User
#                    class:          TaskeetMainBundle:User
#                    primaryKey:     id
#                    exclude:        collection
#                    builder:      { username: username }
#                    matcher:      user.username
builders:
    list:
        params:
            title: Lista de departamentos
            display: [name, slug]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name]
    new:
        params:
            title: Nuevo departamento
            display: [name]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando el departamento \"%object%\"|{ %object%: Department.name }|"
            display: [name, slug, users]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Departamento: \"%object%\"|{ %object%: Department.name }|"
            display: ~
            actions:
                edit: ~
                list: ~
                new: ~
    delete: ~
