generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Department
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    fields: ~

builders:
    list:
        params:
            title: List for MainBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for MainBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    delete: ~
