generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Event
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
#        image:
#            label:            Imagen
#            formType:         single_upload
#            dbType:           string
#            addFormOptions:
#                nameable:       imageLabel
#                data_class:     Symfony\Component\HttpFoundation\File\File
        # startDate:
        #     formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
        # dueDate:
        #     formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType

builders:
    list:
        params:
            title: Eventos
            display: [title, type, startDate, dueDate]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [title, type, startDate, dueDate]
    new:
        params:
            title: Nuevo evento
            display: [title, type, startDate, dueDate, description]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando el evento \"%object%\"|{ %object%: YourModel.title }|"
            display: [title, type, startDate, dueDate, description]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                show: ~
    show:
        params:
            title: "Evento \"%object%\"|{ %object%: YourModel.title }|"
            display: [title, type, startDate, dueDate, description]
            actions:
                list: ~
                edit: ~
                new: ~
    delete: ~
