generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Event
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
#        image:
#            label:            Imagen
#            formType:         single_upload
#            dbType:           string
#            addFormOptions:
#                nameable:       imageLabel
#                data_class:     Symfony\Component\HttpFoundation\File\File

builders:
    list:
        params:
            title: Eventos
            display: [type, title, startDate, dueDate]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [title, type, startDate, dueDate]
    new:
        params:
            title: Nuevo evento
            fields:
                startDate:
                     formType: datepicker
                dueDate:
                     formType: datepicker
            display: [title, type, startDate, dueDate, description]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
            title: "Editando el evento \"%object%\"|{ %object%: Event.title }|"
            fields:
                startDate:
                     formType: datepicker
                dueDate:
                     formType: datepicker
            display: [title, type, startDate, dueDate, description]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
#                show: ~
    show:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
            title: "Evento \"%object%\"|{ %object%: Event.title }|"
            display: [title, type, startDate, dueDate, description]
            actions:
                new: ~
                list: ~
#                edit: ~

    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
