generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Group
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
        roles:
            formType: collection
            dbType: collection
            addFormOptions:
                widget:         table
                allow_add:      true
                allow_delete:   true

builders:
    list:
        params:
            title: Grupos
            display: [name]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name]
    new:
        params:
            credentials: 'hasRole("ROLE_ADMIN")'
            title: Nuevo grupo
            display: [name, roles]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
            title: "You're editing the object \"%object%\"|{ %object%: Group.name }|"
            display: [name, roles]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~

    show:
        params:
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: "%object%|{ %object%: Group.name }|"
            display: [name, roles]
            actions:
                new: ~
                list: ~

    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
