generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Priority
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields: ~

builders:
    list:
        params:
            title: Prioridades
            display: [name]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name]
    new:
        params:
            title: Nueva prioridad
            display: [name]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando la prioridad \"%object%\"|{ %object%: Priority.name }|"
            display: [name]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                show: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Priority.name }|"
            display: [name]
            actions:
                new: ~
                list: ~
#                edit: ~

    delete: ~
