generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Project
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    fields: ~

builders:
    list:
        params:
            title: Lista de proyectos
            display: [name, category, client, startDate, dueDate]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name, category, client, startDate, dueDate]
    new:
        params:
            title: Nuevo proyecto
            display: [name, category, client, startDate, dueDate]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando el proyecto \"%object%\"|{ %object%: Project.name }|"
            display: [name, category, client, startDate, dueDate]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Proyecto \"%object%\"|{ %object%: Project.name }|"
            display: [name, category, client, startDate, dueDate]
            actions:
                list: ~
                new: ~
                edit: ~
    delete: ~
