generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Project
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
        tickets:
            dbType:           collection
            formType:         collection
            addFormOptions:
                widget:       table
                type:         \Taskeet\MainBundle\Form\Type\Ticket\EditType
                allow_add:    true
                allow_delete: true
                by_reference: false
                options:
                    data_class:     Taskeet\MainBundle\Entity\Ticket

builders:
    list:
        params:
            title: Proyectos
#            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            display: [name, category, client, startDate, dueDate]
            scopes:
                group_1:
                    "Todos": ~
                    "Mis proyectos":
                        default: true
                        filters:
                            members: user
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [name, category, client, startDate, dueDate, departments]
    new:
        params:
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: Nuevo proyecto
            fields:
                startDate:
                    formType: datepicker
                dueDate:
                    formType: datepicker
            tabs:
                "General":
                    "NONE": [name, category, client, startDate, dueDate, description]
                "Extras":
                    "Otros": [departments, members]
                "Tareas":
                    "Tareas": [tickets]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando el proyecto \"%object%\"|{ %object%: Project.name }|"
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OPERATOR")'
            fields:
                startDate:
                    formType: datepicker
                dueDate:
                    formType: datepicker
            tabs:
                "General":
                    "NONE": [name, category, client, startDate, dueDate, description]
                "Extras":
                    "Otros": [departments, members]
                "Tareas":
                    "Tareas": [tickets]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
#                show: ~
    show:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "VIEW")'
            title: "%object%|{ %object%: Project.name }|"
            display: [name, category, client, startDate, dueDate, description, departments, members, tickets]
            actions:
                new: ~
                list: ~
#                edit: ~
    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
