dashboard_welcome:
    pattern:  /
    defaults: { _controller: TaskeetMainBundle:Default:index }

taskeet_event_calendar:
    pattern:    /event/calendar
    defaults:   { _controller: TaskeetMainBundle:Event/List:calendar }

select_users:
    pattern: /users
    defaults: { _controller: TaskeetMainBundle:Default:users }

users_by_departament:
    pattern: /departament/users
    defaults: { _controller: TaskeetMainBundle:Default:usersByDepartament }

departaments:
    pattern: /departaments
    defaults: { _controller: TaskeetMainBundle:Default:departments }

ticket_clone:
    pattern: /ticket/clone/{pk}
    defaults: { _controller: TaskeetMainBundle:Ticket/New:clone }

default_priority_ticket:
    pattern: /defaultPriorityStatusTicket
    defaults: { _controller: TaskeetMainBundle:Default:priorityStatusDefault }
