parameters:
#    taskeet_main.example.class: Taskeet\MainBundle\Example

services:
    taskeet_main.profile.type:
        class: Taskeet\MainBundle\Form\Type\User\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: taskeet_main_profile }

    taskeet_main.calendar_listener:
        class: Taskeet\MainBundle\EventListener\CalendarEventListener
        arguments: [@doctrine.orm.entity_manager ]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }

#    taskeet_main.example:
#        class: %taskeet_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


#<services>
#        <service id="acme.demobundle.calendar_listener" class="Acme\DemoBundle\EventListener\CalendarEventListener">
#            <argument type="service" id="doctrine.orm.entity_manager" />
#            <tag name="kernel.event_listener" event="calendar.load_events" method="loadEvents" />
#        </service>