parameters:
#    taskeet_main.example.class: Taskeet\MainBundle\Example

services:
#    taskeet_main.example:
#        class: %taskeet_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
