generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Status
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
        image:
            label:            Imagen
            formType:         single_upload
            dbType:           string
            addFormOptions:
#                nameable:       imageName
                data_class:     Symfony\Component\HttpFoundation\File\File
                thumbnailFilter: mini_thumb

builders:
    list:
        params:
            title: Lista de estados
            display: [image, name, primary]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: [name]
    new:
        params:
            title: Nuevo estado
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            display: [name, primary, image]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando el estado \"%object%\"|{ %object%: Status.name }|"
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OPERATOR")'
            display: [name, primary, image]
            actions:
                save: ~
                list: ~
#    show:
#        params:
#            title: "Estado \"%object%\"|{ %object%: Status.name }|"
#            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
#            display: [name]
#            actions:
#                list: ~
#                new: ~
    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
