generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Ticket
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
        files:
            label:            Archivos
            formType:         upload
            dbType:           collection
            addFormOptions:
                nameable:         name
#                sortable:         position
                editable:         [ name, description ]
                type:             \Taskeet\MainBundle\Form\Type\Media\EditType
                maxNumberOfFiles:           5
                maxFileSize:                5000000
                minFileSize:                10
                acceptFileTypes:            /(\.|\/)(gif|jpe?g|png|txt|doc|docx|pdf|xls|ppt|pptx)$/i
#                previewSourceFileTypes:     /^image\/(gif|jpeg|png)$/
#                previewSourceMaxFileSize:   250000
#                previewMaxWidth:            100
#                previewMaxHeight:           100
#                previewAsCanvas:            true
                prependFiles:               false
                allow_add:        true
                allow_delete:     true
                error_bubbling:   false
                options:
                    data_class:     Taskeet\MainBundle\Entity\Media

builders:
    list:
        params:
            title: Tareas
            sort: [created, DESC]
            display: [status, priority, title, project, assignedTo, startDate, dueDate]
            scopes:
                group_1:
                    "Todas": ~
                    "Mis tareas":
                        default: true
                        filters:
                            assignedTo: user
#                    "Tareas del departamento":
#                            filters:
#                                owner.department: user.department
                    "Finalizadas":
                        filters:
                            done: true
            actions:
                new: ~
            object_actions:
                edit: ~
                show: ~
                delete: ~
    filters:
        params:
            display: [title, project, assignedTo, status, priority,  startDate, dueDate]
    new:
        params:
            title: Nueva tarea
            fields:
                startDate:
                     formType: datepicker
                dueDate:
                     formType: datepicker
            display: [title, priority, status, project, assignedTo, startDate, dueDate, description, files]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando la tarea \"%object%\"|{ %object%: Ticket.title }|"
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OPERATOR")'
            fields:
                startDate:
                    formType: datepicker
                    # credentials: 'hasPermission(object, "OPERATOR")'
                dueDate:
                    formType: datepicker
                    # credentials: 'hasPermission(object, "OPERATOR")'
                # title:
                #     credentials: 'hasPermission(object, "OPERATOR")'
                # priority:
                #      credentials: 'hasPermission(object, "OPERATOR")'
                # project:
                #      credentials: 'hasPermission(object, "OPERATOR")'
                # assignedTo:
                #      credentials: 'hasPermission(object, "OPERATOR")'
            display: [title, priority, status, project, assignedTo, startDate, dueDate, description, done]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
#                show: ~
    show:
        params:
            title: "%object%|{ %object%: Ticket.title }|"
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "VIEW")'
            display: [title, priority, status, project, assignedTo, startDate, dueDate, description, files]
            actions:
                list: ~

    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OPERATOR")'
