generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Ticket
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields: 
        files:
            label:            Archivos
            formType:         upload
            dbType:           collection
            addFormOptions:
                nameable:         name
#                sortable:         position
                editable:         [ name, description ]
                type:             \Taskeet\MainBundle\Form\Type\Media\EditType
                maxNumberOfFiles:           5
                maxFileSize:                5000000
                minFileSize:                10
                acceptFileTypes:            /(\.|\/)(gif|jpe?g|png|doc|docx|pdf|xls|ppt|pptx)$/i
                previewSourceFileTypes:     /^image\/(gif|jpeg|png)$/
                previewSourceMaxFileSize:   250000
                previewMaxWidth:            100
                previewMaxHeight:           100
                previewAsCanvas:            true
                prependFiles:               false
                allow_add:        true
                allow_delete:     true
                error_bubbling:   true
                options:
                    data_class:     Taskeet\MainBundle\Entity\Media

builders:
    list:
        params:
            title: Tareas
            sort: [created, DESC]
            display: [status, title, priority, assignedTo, startDate, dueDate, project]
            fields:
                status:
                    getter: ImageName
            scopes:
                group_1:
                    "Todas": ~
                    "Mis tareas":
                        default: true
                        filters:
                            assignedTo: user
                    "Finalizadas":
                        filters:
                            done: true
            actions:
                new: ~
            object_actions:
                edit: ~
                show: ~
                delete: ~
    filters:
        params:
            display: [title, status, priority, assignedTo, startDate, dueDate, project]
    new:
        params:
            title: Nueva tarea
            fields:
                startDate:
                     formType: datepicker
                dueDate:
                     formType: datepicker
            display: [title, priority, assignedTo, startDate, dueDate, status, project, description, files]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando la tarea \"%object%\"|{ %object%: Ticket.title }|"
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OPERATOR")'
            fields:
                startDate:
                     formType: datepicker
                dueDate:
                     formType: datepicker
            display: [title, priority, assignedTo, startDate, dueDate, status, project, description, files]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
#                show: ~
    show:
        params:
            title: "Tarea \"%object%\"|{ %object%: Ticket.title }|"
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "VIEW")'
            display: ~
            actions:
                new: ~
                list: ~
#                edit: ~

    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OPERATOR")'
