generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\Ticket
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields: 
#        startDate:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
#        dueDate:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
        # files:
        #     label:            Archivo
        #     formType:         single_upload
        #     dbType:           string
        #     addFormOptions:
        #       data_class:     Symfony\Component\HttpFoundation\File\File

builders:
    list:
        params:
            title: Lista de tareas
            display: [title, priority, assignedTo, startDate, dueDate, project]
            actions:
                new: ~
            object_actions:
                edit: ~
                show: ~
                delete: ~
    filters:
        params:
            display: [title, priority, assignedTo, startDate, dueDate, project]
    new:
        params:
            title: Nueva tarea
            fields:
                startDate:
                     formType: datepicker
                dueDate:
                     formType: datepicker
            display: [title, priority, assignedTo, startDate, dueDate, project, description, files]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title: "Editando la tarea \"%object%\"|{ %object%: Ticket.title }|"
            fields:
                startDate:
                     formType: datepicker
                dueDate:
                     formType: datepicker
            display: [title, priority, assignedTo, startDate, dueDate, project, description, files]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                show: ~
    show:
        params:
            title: "Tarea \"%object%\"|{ %object%: Ticket.title }|"
            display: ~
            actions:
                list: ~
                edit: ~
                new: ~
    delete: ~
