generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\User
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    fields:
        password:
            formType:       repeated
            addFormOptions:
                first_options:
                  label:      repeated.label.plainPassword.first
                second_options:
                  label:      repeated.label.plainPassword.second
                type:         password
#        lastLogin:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
        expiresAt:
            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
#        passwordRequestedAt:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
#        credentialsExpireAt:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
        roles:
            formType: collection
            dbType: collection
            addFormOptions:
                widget:         table
                allow_add:      true
                allow_delete:   true


builders:
    list:
        params:
            title: Lista de usuarios
            display: [enabled, username, email, department, created]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [enabled, username, department, lastLogin, created, updated]
    new:
        params:
            title: Nuevo usuario
            display: [username, password, email, department, enabled, expiresAt, roles, projects, tasks]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando el usuario \"%object%\"|{ %object%: User.username }|"
            display: [username, password, email, department, enabled, expired, expiresAt, roles, projects, tasks]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usuario \"%object%\"|{ %object%: User.username }|"
            display: [username, password, email, department, enabled, expired, expiresAt, roles, projects, tasks]
            actions:
                edit: ~
                list: ~
                new: ~
    delete: ~
