generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\User
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
        password:
            formType:       repeated
            addFormOptions:
                first_options:
                  label:      repeated.label.plainPassword.first
                second_options:
                  label:      repeated.label.plainPassword.second
                type:         password
#        lastLogin:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
#        expiresAt:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
#        passwordRequestedAt:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
#        credentialsExpireAt:
#            formType: \Admingenerator\GeneratorBundle\Form\Type\DatePickerType
        roles:
            formType: collection
            dbType: collection
            addFormOptions:
                widget:         table
                allow_add:      true
                allow_delete:   true


builders:
    list:
        params:
            title: Lista de usuarios
            display: [enabled, username, email, department, created]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [enabled, username, department, lastLogin, created, updated]
    new:
        params:
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: Nuevo usuario
            fields:
                expiresAt:
                    formType: datepicker
            tabs:
                "General":
                    "Datos personales": [firstName, lastName, username, password, email, department, enabled, expiresAt]
                "Permisos":
                    "Roles": [roles]
                "Proyectos":
                    "Proyectos": [projects, tasks]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: "Editando el usuario \"%object%\"|{ %object%: User.username }|"
            fields:
                expiresAt:
                    formType: datepicker
            tabs:
                "General":
                    "Datos personales": [firstName, lastName, username, password, email, department, enabled, expired, expiresAt]
                "Permisos":
                    "Roles": [roles]
                "Proyectos":
                    "Proyectos": [projects, tasks]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                show: ~
    show:
        params:
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: "Usuario \"%object%\"|{ %object%: User.username }|"
            display: [firstName, lastName, username, password, email, department, enabled, expired, expiresAt, roles, projects, tasks]
            actions:
                edit: ~
                list: ~
                new: ~
    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN")'
