generator: admingenerator.generator.doctrine
params:
    model: Taskeet\MainBundle\Entity\User
    namespace_prefix: Taskeet
    bundle_name: MainBundle
    i18n_catalog: TaskeetMainBundle
    fields:
        password:
            formType:       repeated
            addFormOptions:
                first_options:
                  label:      repeated.label.plainPassword.first
                second_options:
                  label:      repeated.label.plainPassword.second
                type:         password
        roles:
            formType: collection
            dbType: collection
            addFormOptions:
                widget:         table
                allow_add:      true
                allow_delete:   true


builders:
    list:
        params:
            title: Usuarios
            display: [enabled, username, fullName, department, created]
#            scopes:
#                group_1:
#                    "Todas": ~
#                    "En mi Departamento":
#                        default: true
#                        filters:
#                            departments: user.departments
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [enabled, username, department, groups, created]
    new:
        params:
            credentials: 'hasRole("ROLE_JEFE_DPTO")'
            title: Nuevo usuario
            fields:
                jefeDpto:
                    credentials: 'hasRole("ROLE_ADMIN")'
            tabs:
                "General":
                    "Datos personales": [firstName, lastName, username, password, email, jefeDpto, department, enabled]
                "Permisos":
                    "Roles": [groups]
                "Proyectos":
                    "Proyectos": [projects, tasks]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
            title: "Editando el usuario \"%object%\"|{ %object%: User.username }|"
            fields:
                expiresAt:
                    formType: datepicker
                jefeDpto:
                    credentials: 'hasRole("ROLE_ADMIN")'
            tabs:
                "General":
                    "Datos personales": [firstName, lastName, username, password, email, jefeDpto, department, enabled]
                "Permisos":
                    "Roles": [groups]
                "Proyectos":
                    "Proyectos": [projects, tasks]
            actions:
                save: ~
                save-and-add: ~
                save-and-list: ~
                list: ~
                # show: ~
    show:
        params:
            credentials: 'hasRole("ROLE_ADMIN") or hasRole("ROLE_JEFE_DPTO")'
            title: "%object%|{ %object%: User.username }|"
            display: [firstName, lastName, username, email, jefeDpto, department, enabled, groups, projects, tasks]
            actions:
                 new: ~
#                 edit: ~
                 list: ~

    delete:
        params:
            credentials: 'hasRole("ROLE_SUPER_ADMIN") or hasPermission(object, "OWNER")'
